export default {
    CHARACTERS_LOADED: "CHARACTERS_LOADED",
    CHARACTERS_REQUESTED: "CHARACTERS_REQUESTED",
    METADATA_LOADED: "METADATA_LOADED",
    METADATA_REQUESTED: "METADATA_REQUESTED",
    DETAIL_CHARACTER_SELECTED: "DETAIL_CHARACTER_SELECTED",
}


